# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-09 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_inheritance_ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandFather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('grandfather_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_inheritance_ex.GrandFather')),
                ('fname', models.CharField(max_length=20)),
                ('job', models.BigIntegerField()),
            ],
            bases=('model_inheritance_ex.grandfather',),
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('father_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model_inheritance_ex.Father')),
                ('sname', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
            ],
            bases=('model_inheritance_ex.father',),
        ),
    ]
