# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-09 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inheritance_ex', '0002_father_grandfather_son'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='job',
            field=models.CharField(max_length=20),
        ),
    ]
